//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnMikeTestCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CYCLEFREQUENCY
    {
        public string CYCLEFREQID { get; set; }
        public string OBSASSIGNID { get; set; }
        public string OBSID { get; set; }
        public decimal CYCLEFREQNUMBER { get; set; }
        public string CYCLEFREQCOUNT { get; set; }
    
        public virtual OBSERVATIONASSIGNMENT OBSERVATIONASSIGNMENT { get; set; }
        public virtual OBSERVATION OBSERVATION { get; set; }
    }
}
