//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnMikeTestCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELSTWAREHOUSE
    {
        public ELSTWAREHOUSE()
        {
            this.MACHINEs = new HashSet<MACHINE>();
            this.MACHINETIMINGs = new HashSet<MACHINETIMING>();
            this.OBSERVATIONs = new HashSet<OBSERVATION>();
            this.OBSERVATIONSHEETs = new HashSet<OBSERVATIONSHEET>();
            this.PREFERREDMETHODs = new HashSet<PREFERREDMETHOD>();
        }
    
        public string ELSTWHID { get; set; }
        public string ELSTWHNAME { get; set; }
    
        public virtual ICollection<MACHINE> MACHINEs { get; set; }
        public virtual ICollection<MACHINETIMING> MACHINETIMINGs { get; set; }
        public virtual ICollection<OBSERVATION> OBSERVATIONs { get; set; }
        public virtual ICollection<OBSERVATIONSHEET> OBSERVATIONSHEETs { get; set; }
        public virtual ICollection<PREFERREDMETHOD> PREFERREDMETHODs { get; set; }
    }
}
