//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnMikeTestCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MACHINETIMING
    {
        public string MTID { get; set; }
        public string ELSTWHID { get; set; }
        public string MTMACHINETYPE { get; set; }
        public Nullable<System.DateTime> MTSTARTTIME { get; set; }
        public Nullable<System.DateTime> MTENDTIME { get; set; }
        public string MTDURATION { get; set; }
        public string MTDISTANCE { get; set; }
        public string MTTIMINGTYPE { get; set; }
        public string MTDESC { get; set; }
        public string MID { get; set; }
    
        public virtual ELSTWAREHOUSE ELSTWAREHOUSE { get; set; }
        public virtual MACHINE MACHINE { get; set; }
    }
}
