//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnMikeTestCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBSERVATIONSHEET
    {
        public OBSERVATIONSHEET()
        {
            this.OBSERVATIONs = new HashSet<OBSERVATION>();
            this.OBSERVATIONASSIGNMENTs = new HashSet<OBSERVATIONASSIGNMENT>();
        }
    
        public string OBSSHEETID { get; set; }
        public string ELSTWHID { get; set; }
        public string PREFMETHID { get; set; }
        public string OBSSHEETNAME { get; set; }
        public string OBSSHEETDESC { get; set; }
    
        public virtual ELSTWAREHOUSE ELSTWAREHOUSE { get; set; }
        public virtual ICollection<OBSERVATION> OBSERVATIONs { get; set; }
        public virtual ICollection<OBSERVATIONASSIGNMENT> OBSERVATIONASSIGNMENTs { get; set; }
        public virtual PREFERREDMETHOD PREFERREDMETHOD { get; set; }
    }
}
