//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnMikeTestCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBSERVATION
    {
        public OBSERVATION()
        {
            this.CYCLEFREQUENCies = new HashSet<CYCLEFREQUENCY>();
        }
    
        public string OBSID { get; set; }
        public string ELSTWHID { get; set; }
        public string OBSSHEETID { get; set; }
        public System.DateTime OBSDATETIME { get; set; }
        public string OBSDURATION { get; set; }
        public string OBSNOTES { get; set; }
        public string OBSWARNINGFLAG { get; set; }
    
        public virtual ICollection<CYCLEFREQUENCY> CYCLEFREQUENCies { get; set; }
        public virtual ELSTWAREHOUSE ELSTWAREHOUSE { get; set; }
        public virtual OBSERVATIONSHEET OBSERVATIONSHEET { get; set; }
    }
}
