//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnMikeTestCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBSERVATIONASSIGNMENT
    {
        public OBSERVATIONASSIGNMENT()
        {
            this.CYCLEFREQUENCies = new HashSet<CYCLEFREQUENCY>();
        }
    
        public string OBSASSIGNID { get; set; }
        public string OBSSHEETID { get; set; }
        public string OBSASSIGNDESC { get; set; }
        public decimal OBSASSIGNSEQ { get; set; }
    
        public virtual ICollection<CYCLEFREQUENCY> CYCLEFREQUENCies { get; set; }
        public virtual OBSERVATIONSHEET OBSERVATIONSHEET { get; set; }
    }
}
