//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnMikeTestCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREFERREDMETHOD
    {
        public PREFERREDMETHOD()
        {
            this.OBSERVATIONSHEETs = new HashSet<OBSERVATIONSHEET>();
            this.PREFERREDMETHODLINEs = new HashSet<PREFERREDMETHODLINE>();
        }
    
        public string PREFMETHID { get; set; }
        public string ELSTWHID { get; set; }
        public string PREFMETHNAME { get; set; }
        public string PREFMETHDESC { get; set; }
    
        public virtual ELSTWAREHOUSE ELSTWAREHOUSE { get; set; }
        public virtual ICollection<OBSERVATIONSHEET> OBSERVATIONSHEETs { get; set; }
        public virtual ICollection<PREFERREDMETHODLINE> PREFERREDMETHODLINEs { get; set; }
    }
}
