//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnMikeTestCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREFERREDMETHODLINE
    {
        public string PREFMETHLINEID { get; set; }
        public string PREFMETHID { get; set; }
        public string PREFMETHLINEDESC { get; set; }
        public decimal PREFMETHLINESEQ { get; set; }
    
        public virtual PREFERREDMETHOD PREFERREDMETHOD { get; set; }
    }
}
