//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JohnMikeTestCode.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Test : DbContext
    {
        public Test()
            : base("name=Test")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Employee> Employees { get; set; }
        public DbSet<CYCLEFREQUENCY> CYCLEFREQUENCies { get; set; }
        public DbSet<ELSTWAREHOUSE> ELSTWAREHOUSEs { get; set; }
        public DbSet<MACHINE> MACHINEs { get; set; }
        public DbSet<MACHINETIMING> MACHINETIMINGs { get; set; }
        public DbSet<OBSERVATION> OBSERVATIONs { get; set; }
        public DbSet<OBSERVATIONASSIGNMENT> OBSERVATIONASSIGNMENTs { get; set; }
        public DbSet<OBSERVATIONSHEET> OBSERVATIONSHEETs { get; set; }
        public DbSet<PREFERREDMETHOD> PREFERREDMETHODs { get; set; }
        public DbSet<PREFERREDMETHODLINE> PREFERREDMETHODLINEs { get; set; }
    }
}
